
library(shiny)
source("define_plots_and_functions.R")


## Some different labels and titles ----------------------------------
chart.type.list <- list("Total electricity generation" = 1,
                        "Percent of electricity generated by different energy sources" = 2,
                        "Per-capita energy generation" = 3)

data_and_sources <- paste0("Data and sources: data on electricity ",
                           "sources comes from the ",
                           "<a href='https://data.worldbank.org/indicator/EG.ELC.NGAS.ZS'>World Bank Microdata Catalog</a>",
                           ", accessed on 16 July ",
                           "2019. Other data are from the ",
                           "<a href='https://www.eia.gov/beta/international/data/browser/#/?pa=0000002000000000000007vo70400fvu2&c=200m0061so020h00hbg0000408g446dc00000002ca86c030003k&ct=0&ug=8&tl_id=2-A&vs=INTL.2-2-AGO-BKWH.A&cy=2015&vo=0&v=H&end=2017'>International Energy Statistics</a> database, ",
                           "accessed on 20 July 2019.",
                           "<br>",
                           "<br>")

## Define UI ---------------------------------------------------------
ui <- fluidPage(

  # App title ----
    titlePanel(
        list(tags$img(src="CEOGLogoFinal_Color.png",
                      height='90px'),
             "CEoG Data Story - Electricity in Africa"),

        windowTitle = "CEoG Data Story - Electricity"),

    em("Please allow about 10 seconds for loading"),

    HTML('<br><br>'),

    tabsetPanel(
        type = "tabs",

        tabPanel("Aggregate information",
                 fluidRow(style='padding:15px;',
                 radioButtons("figure_type",
                              h3(paste0("Choose information to plot ",
                                        "for all countries")),
                              choices = chart.type.list,
                              selected = 1,
                              width = '100%'),
                 conditionalPanel(
                     condition =  "input.figure_type == 1",

                     column(10,
                            h5("Countries generating less than 5 Billion kWh per year"),
                            fluidRow(style="",
                                     plotOutput(outputId="distPlot1",  height  = 500)),
                            h5("Countries generating between 5 and 10 Billion kWh per year"),
                            fluidRow(
                                plotOutput(outputId="distPlot2",
                                           height = 500)),
                            h5("Countries generating between 10 and 30 Billion kWh per year"),
                            fluidRow(style="background-color:white",
                                     plotOutput(outputId="distPlot3",
                                                height = 350)),
                            h5("South Africa generates about one-third of the total energy generated in Africa, in a similar range to SE Asia comparators"),
                            fluidRow(
                                plotOutput(outputId="distPlot4",
                                           height = 500))

                            )
                 ),

                 conditionalPanel(
                     condition =  "input.figure_type == 2",

                     column(10,
                            h5("Percentage of total electricity generation by energy source"),
                            plotOutput(outputId="percentPlot",
                                       height  = 1000))
                 ),
                 conditionalPanel(
                     condition =  "input.figure_type == 3",

                     column(10,
                            h5(paste0("Electricity generated per capita, ",
                                      "Africa and South East Asian comparators")),
                            plotOutput(outputId="percapitaPlot",
                                       height  = 1000))
                 )),
                 HTML(paste("<br><br>", data_and_sources))),

        tabPanel("Country-specific information",
                 selectInput("country_select_input",

                             h3("Select box"),
                             choices = country.list),


                 fluidRow(
                     column(6,
                            h4(textOutput(outputId="killer_fridge")),
                            plotOutput(outputId="country_consumption_plot")),
                     column(4,
                            h4(textOutput(outputId="but_access")),
                            plotOutput(outputId="waffle"))
                 ),
                 fluidRow(style='padding:10px;',
                     h4(textOutput(outputId="export_text")),
                     plotOutput(outputId="production_breakdown_plot")),
                 HTML(data_and_sources))
    ,
      tabPanel("Additional information",
               h2("CEoG Resources"),
               h6("Access is reserved for members of the CEoG Network"),
               tags$a(href="https://www.africaceog.org/advisor-profiles",
                      paste0("Read profiles of advisors who have ",
                             "tackled policy issues related to energy ",
                             "and electricity.")),
               h2("Further Reading"),
               tags$ul(
                        tags$li(tags$a(href="https://worldbankgroup.sharepoint.com/sites/wbsites/akl/Pages/Electricity-Access-in-SubSaharan-Africa-Uptake-Reliability-and-Complementary-Factors-for-Economic-Impact-07082019-114125.aspx",
                               paste0("Electricity Access in sub-Saharan Africa")))
                       ,
                        tags$li(tags$a(href="https://www.energyforgrowth.org",
                               "Energy for Growth")
                    ))

      ))
)


server <- function(input, output) {

    output$distPlot1 <- renderPlot({
        energy.mix.plots[[1]]
    },
    height = 450)

    output$distPlot2 <- renderPlot({
        energy.mix.plots[[2]]

    },
    height = 450)

    output$distPlot3 <- renderPlot({
        energy.mix.plots[[3]]
    },
    height = 350)


    output$distPlot4 <- renderPlot({
        energy.mix.plots[[4]]
    },
    height = 350)

    output$percentPlot <- renderPlot({
        energy.mix.percentages.plot
    })

    output$percapitaPlot <- renderPlot({
        per.capita.plot
    })

    output$country_consumption_plot <- renderPlot({
        country.idx <- as.numeric(input$country_select_input)
        country.name <- names(country.list[country.idx])

        plot.out <- make.country.consumption.plot(country.name)
        return(plot.out)
    })

    output$waffle <- renderPlot({
        country.idx <- as.numeric(input$country_select_input)
        country.name <- names(country.list[country.idx])

        plot.out <- make.country.waffle.plot(country.name)
        return(plot.out)
    })

    output$production_breakdown_plot<- renderPlot({
        country.idx <- as.numeric(input$country_select_input)
        country.name <- names(country.list[country.idx])

        plot.out <- make.production.plot(country.name)
        return(plot.out)
    },
    height = 310)

    output$killer_fridge <- renderText({
        country.idx <- as.numeric(input$country_select_input)
        country.name <- names(country.list[country.idx])

        fact <- calculate.killer.fact(country.name)

        text.out <- sprintf(killer.fridge,
                            fact$year,
                            fact$country,
                            fact$nationality,
                            round(fact$fridges, 0))
        return(text.out)
    })

      output$but_access <- renderText({
          country.idx <- as.numeric(input$country_select_input)
          country.name <- names(country.list[country.idx])

          fact <- calculate.but_access.fact(country.name)

          text.out <- sprintf(but.access, fact)

        return(text.out)
      })

    output$export_text <- renderText({
        country.idx <- as.numeric(input$country_select_input)
        country.name <- names(country.list[country.idx])

        fact <- calculate.export(country.name)

        text.out <- sprintf(net.export.text, country.name, fact)

        return(text.out)
    })



}

shinyApp(ui = ui, server = server)

